### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by gearcapitan** [mdsecactivebreach/SharpShooter#1]
![kali_linux-2018-03-07-21-57-34](https://user-images.githubusercontent.com/13740942/37132271-a00efb06-2252-11e8-8242-9c786a8bad45.png)

**Comment by gearcapitan** [comment]
the solution is manual

pip install jsmin

done!

**Comment by dmchell** [comment]
I provided the requirements.txt file - you can pip install -r that

**Comment by S4lt5** [comment]
In Kali 2022 you can python2 -m pip install jsmin==2.2.2 

It kept giving me problems with the requirements.txt file , no idea why...

**Comment by jieliau** [comment]
@Yablargo it's due to setuptools 58 added a breaking change to remove use_2to3 support. Please refer to here: https://github.com/tikitu/jsmin/issues/33

Try apt-get install python3-jsmin
