### ISSUE TITLE
clean pull of the src does not appear to work with python 3 on stock kali

### ISSUE THREAD

**Issue by TheRealSuser** [mdsecactivebreach/SharpShooter#11]
appears to have some compatibility issues with python 3 and 3.6.  Running through the HTA payload generation causes a python error with Strings module.

Additionally when running a fresh pull with python 2.7 it will not accept a uri for the HTA payload.  

I've forked the repo and have started trying to fix the bugs myself but wanted to make MDsec aware of the issues

Thanks for an amazing tool!

**Comment by dmchell** [comment]
Python3 will require further testing - support was added from a PR, I've only extensively tested on 2.7.

What's the cmd line you're using for the issue with the URI on HTA?

**Comment by syedhamaid** [comment]
[Errno 2] No such file or directory: './raw.txt'
 how to fix this
