### ISSUE TITLE
[!] Missing --dotnetver argument

### ISSUE THREAD

**Issue by UN5T48L3** [mdsecactivebreach/SharpShooter#14]
Hey!
I've already installed dotnet on my Kali Linux but still I can't start the SharpShooter.
When I run python SharpShooter.py It shows this error.

![ekran resmi 2018-07-24 18 19 46](https://user-images.githubusercontent.com/39417235/43148732-94b10ae0-8f6e-11e8-9847-01569116c426.png)

**Comment by dmchell** [comment]
I think you misunderstand, --dotnet is an argument - the script is telling you that this argument is required. You probably want to RTFM.
