### ISSUE TITLE
Correct Reg path for AMSI commit?

### ISSUE THREAD

**Issue by jmhickman** [mdsecactivebreach/SharpShooter#16]
I was looking at your recent commit adding the AMSI bypass for VB and JS methods, and looked for the reg path `HKCU\Software\Microsoft\Windows Script\Settings\` on my 1803 Windows machine, and couldn't find it. There is a `HKCU\Software\Microsoft\Windows Script Host\Settings\` key however.

Just wanted to make sure that the path wasn't in error.

**Comment by dmchell** [comment]
It's right, the key doesn't exist by default but is generated by my RegWrite...
